name: Python-Style-Guide-Get-Original

on:
  schedule:
    # 매주 금요일 18:00에 실행합니다. (UTC +09:00) 
    - cron:  '0 9 * * 5'
  issues:
    # 이슈에 새로운 항목이 생기거나 수정사항이 있으면 실행합니다.
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./script/update_original_requirements.txt ]; then pip install -r ./script/update_original_requirements.txt; fi
      - name: Crawler
        run: |
          python ./script/update_original.py
        env:
          # Settings > sercets > ACCESS_TOKEN
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
