name: Python-Style-Guide-Get-Original

on:
  schedule:
    # 1, 4, 7, 10월 첫 금요일에 실행합니다. (UTC +09:00)
    - cron: "0 0 1-7 1,4,7,10 5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./script/update_original_requirements.txt ]; then pip install -r ./script/update_original_requirements.txt; fi
      - name: Crawler
        run: |
          python ./script/update_original.py
        env:
          # Settings > sercets > ACCESS_TOKEN
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
